### ISSUE TITLE
Multiple Deployment is not work

### ISSUE THREAD

**Issue by whzecomjm** [hexojs/hexo-deployer-openshift#2]
I am using the most updated version of node.js and hexo, and I'd like to deploy my blog into both openshift and CNPaaS(with openshift deployment). 

When I write down:
~~~
    deploy:
      type: openshift
      repo: XXXX@en-whzecomjm.app.cnpaas.io:~/git/en.git
      repo: ssh://XXXX@en-whzecomjm.rhcloud.com/~/git/en.git/
~~~
which only deploy the last one but not cnpaas.

Is any thing wrong here in my config or just there is a bug here?

**Comment by tommy351** [comment]
You can't have two values with the same key in YAML. Try this instead:

``` yaml
deploy:
  - type: openshift
    repo: ...
  - type: openshift
    repo: ...
```
